export { default as Home } from './Home.jsx'
export { default as Profile } from './Profile.jsx'
export { default as Dashboard } from './Dashboard.jsx'
export { default as Doubts } from './Doubts.jsx'
export { default as DoubtDetails } from './DoubtDetails.jsx'
export { default as ChatRoom } from './ChatRoom.jsx'
